# Generated by Django 3.2.4 on 2021-08-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroke', '0002_alter_imageuploadmodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='document',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
