# Generated by Django 3.2.4 on 2021-07-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stroke', '0002_auto_20210720_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadmodel',
            name='uploaded_at',
        ),
    ]
