# Generated by Django 3.2.4 on 2021-07-21 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stroke', '0003_remove_imageuploadmodel_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadmodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='document',
            field=models.ImageField(upload_to=''),
        ),
    ]
