# Generated by Django 3.2.4 on 2021-08-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroke', '0004_alter_imageuploadmodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='document',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
