# Generated by Django 3.2.4 on 2021-07-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroke', '0004_auto_20210722_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='document',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
