# Generated by Django 3.2.4 on 2021-08-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stroke', '0007_alter_imageuploadmodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='document',
            field=models.TextField(null=True),
        ),
    ]
